version: '3.8'

services:
  mongo:
    image: mongo:4.2.10
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - $HOME/mongo:/data/db
    healthcheck:
      test: "exit 0"

  superhero-service:
    container_name: smdc-crud-superhero-service
    build: superhero-service
    environment:
      - spring.data.mongodb.host=mongo    
      - SWAGGER_URL=/swagger-ui.html
      - API_URL=http://localhost:8088/v2/api-docs
    volumes:
      - ./swagger-ui:/usr/share/nginx/html
    command: ["nginx", "-g", "daemon off;"]
    image: superhero-service
    depends_on:
      - mongo
    restart: always
    ports:
      - 8088:8088      
      - 8080:8080
    healthcheck:
      test: "exit 0"
